import streamlit as st
from PIL import Image
import google.generativeai as genai
import os
import sqlite3 
import speech_recognition as sr
from dotenv import load_dotenv
import pandas as pd 

# ----------------- CONFIGURATION -----------------
DATABASE_NAME = 'knowledge.db'
# Public URL for the background image
BACKGROUND_IMAGE_URL = 'https://res.cloudinary.com/dwwdoho6m/image/upload/v1761983422/pexels-pixabay-265216_ydcbqs.jpg'

# Hardcoded authentication (Replace with database or Firebase check in production)
USERS = {"Nandu": "Nandu123", "farmer": "pass"} 

# ----------------- DATABASE CONNECTION (FIXED FOR STREAMLIT THREADING) -----------------

@st.cache_resource
def get_db_connection():
    """Establishes and caches the database connection safely for Streamlit."""
    try:
        conn = sqlite3.connect(DATABASE_NAME, check_same_thread=False)
        conn.row_factory = sqlite3.Row 
        return conn
    except sqlite3.Error as e:
        st.error(f"FATAL: Database connection failed. Ensure '{DATABASE_NAME}' exists. Error: {e}")
        return None

# ----------------- DATABASE VIEW FUNCTION -----------------

def show_knowledge_base():
    """Fetches all data from the diseases table and displays it."""
    conn = get_db_connection()
    
    st.markdown("## 📊 Offline Knowledge Base Contents")
    st.info(f"Displaying all entries in the '{DATABASE_NAME}' database. This data was generated by the Gemini API.")
    
    if not conn:
        st.error("Cannot display data: Database connection is not available.")
        return

    try:
        df = pd.read_sql_query("SELECT * FROM diseases", conn)
        st.dataframe(df, use_container_width=True)

        st.markdown("### Data Structure Explanation")
        st.markdown("""
        - **disease_key:** The standardized internal name.
        - **lang_code:** The language of the content.
        """)

    except pd.io.sql.DatabaseError as e:
        st.error(f"Error fetching data from database. Has the table been created? **Run 'python generate_full_db_data.py' first.** Error: {e}")
    except Exception as e:
        st.error(f"An unexpected error occurred while displaying the database: {e}")
        
# ----------------- SPEECH-TO-TEXT FUNCTION (OFFLINE) -----------------
def get_voice_input(lang_code):
    # Implementation remains the same
    r = sr.Recognizer()
    st.info("🎙️ Listening... Please speak your crop issue clearly.")
    
    sphinx_lang = 'en-US' 
    if lang_code == 'hi':
        sphinx_lang = 'hi-IN'

    try:
        with sr.Microphone() as source:
            r.adjust_for_ambient_noise(source)
            audio = r.listen(source, timeout=5)
            
        st.write("Processing audio locally...")
        
        text = r.recognize_sphinx(audio, language=sphinx_lang) 
        return text

    except sr.WaitTimeoutError:
        st.warning("No speech detected after 5 seconds. Please try again or type.")
        return None
    except sr.UnknownValueError:
        st.warning(f"Offline speech engine ({sphinx_lang}) could not understand audio. Try typing or changing language.")
        return None
    except Exception as e:
        st.error(f"An unexpected error occurred during recording/processing: {e}")
        return None


# ----------------- AUTHENTICATION HANDLERS -----------------
def authenticate_user(username, password):
    """Checks credentials against the hardcoded dictionary."""
    if username in USERS and USERS[username] == password:
        st.session_state['authenticated'] = True
        st.session_state['username'] = username
        st.session_state['page'] = 'advisor' # Go to main page after login
        st.success(f"Welcome, {username.capitalize()}!")
        st.rerun()
    else:
        st.error("Invalid username or password.")

def logout():
    """Resets authentication state."""
    st.session_state['authenticated'] = False
    st.session_state['username'] = None
    st.session_state['page'] = 'login'
    st.rerun()


# ----------------- ENVIRONMENT SETUP -----------------
load_dotenv()
try:
    genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
    MODEL = genai.GenerativeModel("gemini-2.5-flash") 
except Exception as e:
    MODEL = None
    
# Language mapping and fallback texts
LANG_MAP = {
    "English": "en",
    "हिंदी (Hindi)": "hi",
    "తెలుగు (Telugu)": "te"
}
FALLBACK_ADVICE_EN = "Could not find a match in the local knowledge base. Please refine your symptoms."
FALLBACK_ADVICE_HI = "स्थानीय डेटाबेस में कोई मिलान नहीं मिला। कृपया अपने लक्षणों को और स्पष्ट करें।"
FALLBACK_ADVICE_TE = "స్థానిక డేటాబేస్లో సరిపోలేది కనుగొనబడలేదు. దయచేసి మీ లక్షణాలను మెరుగుపరచండి।"

# ----------------- SESSION STATE INITIALIZATION -----------------
if 'authenticated' not in st.session_state:
    st.session_state['authenticated'] = False
if 'username' not in st.session_state:
    st.session_state['username'] = None
if 'page' not in st.session_state:
    st.session_state.page = 'login'


# ----------------- PAGE CONFIG -----------------
st.set_page_config(
    page_title="Krishi Sajag — AI Crop Advisor",
    page_icon="🌾",
    layout="wide"
)

# ----------------- PAGE STYLE (Aesthetic Improvements + Background Image) -----------------
page_style = f"""
<style>
/* ---------------------------------------------------- */
/* BACKGROUND IMAGE & TRANSPARENCY FIX */
/* ---------------------------------------------------- */
[data-testid="stAppViewContainer"] {{
    /* Base Color/Overlay */
    background-color: #f0fff0; 
    
    /* 🌟 Background Image */
    background-image: url('{BACKGROUND_IMAGE_URL}');
    background-size: cover; 
    background-repeat: no-repeat;
    background-attachment: fixed;
    
    color: #2b2b2b;
    font-family: 'Segoe UI', sans-serif;
}}

/* Make the main content block semi-transparent white for readability */
[data-testid="stVerticalBlock"] {{
    background-color: rgba(255, 255, 255, 0.85); 
    padding: 20px;
    border-radius: 15px;
}}
/* ---------------------------------------------------- */

/* Sidebar styling */
[data-testid="stSidebar"] {{
    background-color: #1a4314 !important;
    color: #f3f3f3 !important;
}}

/* Sidebar Headings (Menu, Navigation) */
[data-testid="stSidebar"] h1, [data-testid="stSidebar"] h2, [data-testid="stSidebar"] h3 {{
    color: #4CAF50 !important; 
}}

/* 🌟 NEW FIX: Force background of radio options to dark green for visibility */
[data-testid="stSidebar"] [data-testid="stRadio"] label {{
    background-color: #4CAF50 !important; /* Dark green background */
    border-radius: 5px;
    padding: 5px;
    margin-bottom: 3px;
    transition: background-color 0.2s;
}}

/* CRITICAL FIX FOR SIDEBAR TEXT & LABELS */
/* General text/list items (like the footer) remain white */
[data-testid="stSidebar"] ul li, [data-testid="stSidebar"] p {{
    color: #ffffff !important; 
}}
/* General sidebar labels remain white */
[data-testid="stSidebar"] label {{
    color: #4CAF50 !important; 
}}

/* Target the language radio button options with high specificity (Keeps text green) */
[data-testid="stSidebar"] .stRadio label > div > span {{
    color: #4CAF50 !important; 
    font-weight: 600 !important; 
}}

/* Title and subtitles */
.title {{
    font-size: 100px; 
    text-align: center;
    color: #388e3c; 
    font-weight: 900; 
    margin-top: 10px;
}}
.subtitle {{
    text-align: center;
    color: #555;
    font-size: 20px;
    margin-bottom: 25px;
}}

/* Input boxes and text areas */
div.stTextArea textarea {{
    background-color: #ffffff;
    color: #1a1a1a;
    border-radius: 12px;
    border: 1px solid #a5d6a7;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);
    transition: all 0.3s ease-in-out;
}}

/* Buttons */
div.stButton > button:first-child {{
    background-color: #4CAF50; 
    color: white;
    border-radius: 12px;
    height: 3.5em; 
    width: 100%;
    font-weight: 700;
    transition: all 0.3s ease-in-out;
}}
div.stButton > button:first-child:hover {{
    background-color: #388e3c;
    transform: scale(1.01);
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
}}

/* Ensure the text inside ALL buttons (sidebar included) is WHITE */
div.stButton button div span {{
    color: #ffffff !important;
}}

/* Styling the Login Form Box */
[data-testid="stSidebar"] [data-testid="stForm"] {{
    border: 2px solid #4CAF50 !important; 
    border-radius: 10px;
    padding: 10px 15px !important;
    background-color: #2b5726; 
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);
    margin-bottom: 20px;
}}

/* Styling the Login Button */
[data-testid="stSidebar"] [data-testid="stForm"] div.stButton button {{
    background-color: #FFC107 !important; 
    color: #1a1a1a !important; 
    font-weight: 700 !important;
    height: 2.5em; 
}}
[data-testid="stSidebar"] [data-testid="stForm"] div.stButton button:hover {{
    background-color: #FFD700 !important;
}}

/* Section Divider Style */
.section-divider {{
    border: none;
    height: 2px;
    background-color: #d0e8d0; 
    margin: 30px 0;
    width: 100%;
    opacity: 0.7;
}}

/* Footer */
footer {{visibility: hidden;}}
</style>
"""
st.markdown(page_style, unsafe_allow_html=True)

# ----------------- HEADER -----------------
st.markdown('<p class="title">🌾 Krishi Sajag</p>',unsafe_allow_html=True)
st.markdown('<p class="subtitle">Your Smart AI Crop Advisor for Rural India</p>', unsafe_allow_html=True)
st.markdown("<br>", unsafe_allow_html=True)

# ----------------- SIDEBAR (Authentication and Navigation) -----------------
with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/2909/2909767.png", width=90)
    st.title("🌱 Menu")

    if st.session_state['authenticated']:
        # Authenticated Menu
        st.markdown(f"### 👋 Welcome, {st.session_state['username'].capitalize()}")
        st.markdown("### 🗺️ Navigation:")
        
        if st.button("🧠 AI Crop Advisor", key="nav_advisor"):
            st.session_state.page = 'advisor'
        if st.button("📊 View Knowledge Base", key="nav_database"):
            st.session_state.page = 'database'
        
        st.markdown("---")
        
        # Language Selector (only shown on the advisor page)
        if st.session_state.page == 'advisor':
            st.markdown("### 🌐 Select Language:")
            selected_language = st.radio(
                "Choose Advice Language:",
                options=list(LANG_MAP.keys()),
                index=1, 
                key="language_selector"
            )
            current_lang_code = LANG_MAP[selected_language]
        else:
            selected_language = "English"
            current_lang_code = "en"
            
        st.markdown("---")
        st.button("🔒 Logout", on_click=logout, key="logout_btn")
        
    else:
        # Login Form (Not Authenticated)
        st.markdown("### 🔑 Login to Krishi Sajag")
        with st.form("login_form"):
            st.text_input("Username", key="login_username", placeholder="Enter username")
            st.text_input("Password", type="password", key="login_password", placeholder="Enter password")
            
            submitted = st.form_submit_button("Login")
            
            if submitted:
                # Call authentication handler
                authenticate_user(st.session_state['login_username'], st.session_state['login_password'])
                
        st.info("Demo User: Nandu / Nandu123")
        
    st.markdown("---")
    st.caption("Built by Nandu • Powered by Gemini 🌿")

# ----------------- MAIN CONTENT RENDERER -----------------

if not st.session_state['authenticated']:
    # Show welcome message/login prompt on the main screen if not authenticated
    st.empty()
    st.markdown("<br><br><h2>Please login in the sidebar to access the AI Crop Advisor.</h2>", unsafe_allow_html=True)

else: # User is authenticated
    if st.session_state.page == 'database':
        show_knowledge_base()

    else: # Default to 'advisor' page
        # ----------------- SECTION 1 (DESCRIPTION) -----------------
        with st.container(border=True): 
            st.markdown("## 1. 🌿 Describe Your Crop Issue")
            st.write(f"Please enter the symptoms of your plant OR use the voice input. Advice will be generated in: **{selected_language}**.")

            col1, col2 = st.columns([2, 1])

            with col1:
                if 'user_query_text_area' not in st.session_state:
                    st.session_state.user_query_text_area = ""
                    
                user_query = st.text_area(
                    "Type your issue here:",
                    placeholder="Example: My tomato leaves are turning yellow and have brown spots...",
                    height=150,
                    key="user_query_text_area"
                )
                
                if st.button("🎤 Use Voice Input (Offline)", key="voice_button_main"):
                    voice_text = get_voice_input(current_lang_code)
                    if voice_text:
                        st.session_state.user_query_text_area = voice_text
                        st.rerun()
                
        # ----------------- SECTION SEPARATOR -----------------
        st.markdown('<hr class="section-divider">', unsafe_allow_html=True)

        # ----------------- SECTION 2 (IMAGE UPLOAD) -----------------
        with st.container(border=True): 
            st.markdown("## 2. 📸 Upload a Photo (Optional)")
            st.write("A clear photo of the leaf or plant helps the AI confirm the diagnosis.")

            uploaded_file = st.file_uploader("Upload crop/leaf photo", type=["jpg", "jpeg", "png"])

            if uploaded_file:
                image = Image.open(uploaded_file)
                st.image(image, caption="Uploaded Image", width=300)

        # ----------------- SECTION SEPARATOR -----------------
        st.markdown('<hr class="section-divider">', unsafe_allow_html=True)

        # ----------------- SECTION 3 (ANALYSIS) -----------------
        st.markdown("## 3. 🌱 Get AI Diagnosis")
        st.write("Click the button below to analyze your input and receive localized remedies.")

        # ----------------- DIAGNOSIS FUNCTION (Queries the SQLite DB) -----------------
        def get_offline_advice(query, lang_code):
            """Queries the SQLite database for a matching diagnosis and advice."""
            conn = get_db_connection()
            if not conn:
                return None 

            query = query.lower()
            diagnosis_key = None
            
            # NOTE: This is the current keyword matching logic (Needs expansion/ML)
            if "rice" in query or "blast" in query:
                diagnosis_key = "Rice Blast"
            elif "wheat" in query or "rust" in query:
                diagnosis_key = "Wheat Rust"
            elif "cotton" in query or "bollworm" in query:
                diagnosis_key = "Cotton Bollworm"
            elif "potato" in query or "blight" in query:
                diagnosis_key = "Potato Late Blight"
            elif "yellow" in query or "zinc" in query:
                diagnosis_key = "Zinc Deficiency"
            
            if diagnosis_key:
                cursor = conn.cursor()
                cursor.execute(
                    "SELECT disease_name, cause, symptoms, remedies, preventive FROM diseases WHERE disease_key = ? AND lang_code = ?",
                    (diagnosis_key, lang_code)
                )
                row = cursor.fetchone()
                
                if row:
                    return dict(row)
                
            return None

        # ----------------- AI ANALYSIS -----------------

        if st.button("✨ Start AI Diagnosis"):
            query = st.session_state.user_query_text_area if 'user_query_text_area' in st.session_state else ""
            
            if not query and not uploaded_file:
                st.warning("⚠️ Please **describe** a crop issue or **upload** a photo in the sections above.")
            else:
                with st.spinner("Analyzing your crop issue using local knowledge... 🌿"):
                    
                    advice = get_offline_advice(query, current_lang_code)
                    
                    if advice:
                        st.success(f"✅ Diagnosis Found (Offline in {selected_language})!")
                        
                        # Dynamic header creation logic
                        if current_lang_code == 'hi':
                            symptom_header = "#### 🔍 Symptoms / लक्षण"
                            cause_header = "#### 🤔 Cause / कारण"
                            remedy_header = "#### 💊 Remedies (Low-Cost/Organic) / उपचार"
                            preventive_header = "#### 🛡️ Preventive Measures / रोकथाम"
                        elif current_lang_code == 'te':
                            symptom_header = "#### 🔍 Symptoms / లక్షణాలు"
                            cause_header = "#### 🤔 Cause / కారణం"
                            remedy_header = "#### 💊 Remedies (Low-Cost/Organic) / నివారణ"
                            preventive_header = "#### 🛡️ Preventive Measures / నివారణ చర్యలు"
                        else:
                            symptom_header = "#### 🔍 Symptoms"
                            cause_header = "#### 🤔 Cause"
                            remedy_header = "#### 💊 Remedies (Low-Cost/Organic)"
                            preventive_header = "#### 🛡️ Preventive Measures"

                        st.markdown(f"### 🌾 {advice['disease_name']} — Suggested Diagnosis & Remedies")
                        
                        st.markdown(symptom_header)
                        st.info(advice['symptoms']) 
                        
                        st.markdown(cause_header)
                        st.write(advice['cause'])
                        
                        st.markdown(remedy_header)
                        st.success(advice['remedies'])
                        
                        st.markdown(preventive_header)
                        st.write(advice['preventive'])

                    else:
                        st.warning("⚠️ Local match failed. Attempting to use live AI (requires internet/API).")
                        
                        # Fallback text logic
                        if current_lang_code == 'hi':
                            fallback_text = FALLBACK_ADVICE_HI
                        elif current_lang_code == 'te':
                            fallback_text = FALLBACK_ADVICE_TE
                        else:
                            fallback_text = FALLBACK_ADVICE_EN

                        if MODEL:
                            # FALLBACK TO LIVE GEMINI
                            try:
                                prompt = f"""
                                You are an expert agricultural advisor helping farmers detect and fix crop diseases.
                                Based on the farmer's input, provide a likely disease name, cause, organic remedies, and preventive measures.
                                **Translate the entire response into {selected_language}.**
                                Farmer's input: {query}
                                """
                                response = MODEL.generate_content(prompt)
                                st.success("✅ AI Analysis Complete (Online Fallback)!")
                                st.markdown(f"### 🌾 Suggested Diagnosis & Remedies\n{response.text}")
                            except Exception as e:
                                st.error(f"❌ Error during online AI analysis: {fallback_text}")
                        else:
                            st.error(f"❌ Gemini Model is not configured or there is no internet connection. Cannot provide diagnosis. {fallback_text}")
